# Generated by Django 2.0.2 on 2018-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_romans_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='romans_lesson',
            name='iden',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
