# Generated by Django 2.0.2 on 2018-02-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_romans_lesson_iden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romans_lesson',
            name='iden',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
