# Generated by Django 2.0.2 on 2018-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180221_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romans_lesson',
            name='iden',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='romans_lesson',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
