# Generated by Django 2.0.2 on 2018-02-21 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180221_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Romans_lesson',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
